// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003085203_Seed13Books")]
    partial class Seed13Books
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Entity.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            FullName = "Quản Trị Viên Hệ Thống",
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            AccountId = 2,
                            FullName = "Nguyễn Văn Khách",
                            Password = "123456",
                            Role = "User",
                            Username = "khachhang"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Entity.AdminNotification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderFormId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("NotificationId");

                    b.HasIndex("OrderFormId");

                    b.ToTable("AdminNotifications");
                });

            modelBuilder.Entity("WebApplication1.Models.Entity.BookInfomation", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookId"));

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("DetailAuthor")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("InformationAuthor")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("TitleReview")
                        .HasColumnType("text");

                    b.HasKey("BookId");

                    b.ToTable("BookInfomations");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            BookName = "Nhà Giả Kim (The Alchemist)",
                            Category = "Văn học kinh điển",
                            DetailAuthor = "Paulo Coelho - Nhà văn huyền thoại người Brazil, Sứ giả hòa bình của Liên Hợp Quốc.",
                            ImageUrl = "/images/nha-gia-kim.png",
                            InformationAuthor = "Tác giả có sách được dịch ra nhiều thứ tiếng nhất lịch sử (Kỷ lục Guinness thế giới).",
                            Price = 79000m,
                            Subtitle = "Khi bạn thực sự khao khát một điều gì, toàn thể vũ trụ sẽ hợp lực giúp bạn đạt được điều đó.",
                            Title = "Hành Trình Đi Tìm Vận Mệnh & Giấc Mơ",
                            TitleReview = "Kiệt tác văn học kinh điển toàn cầu đã lay động hơn 150 triệu độc giả trên 170 quốc gia."
                        },
                        new
                        {
                            BookId = 2,
                            BookName = "Đắc Nhân Tâm (How to Win Friends)",
                            Category = "Kỹ năng sống",
                            DetailAuthor = "Dale Carnegie - Chuyên gia phát triển nhân cách và nghệ thuật giao tiếp hàng đầu nước Mỹ.",
                            ImageUrl = "/images/dac-nhan-tam.png",
                            InformationAuthor = "Nhà sáng lập Viện Đào tạo Dale Carnegie toàn cầu.",
                            Price = 86000m,
                            Subtitle = "Cuốn sách hay nhất của mọi thời đại đưa bạn đến thành công và hạnh phúc đích thực.",
                            Title = "Nghệ Thuật Thu Phục Lòng Người & Đối Nhân Xử Thế",
                            TitleReview = "Tác phẩm bán chạy nhất mọi thời đại với hơn 30 triệu bản in trên toàn cầu."
                        },
                        new
                        {
                            BookId = 3,
                            BookName = "Nghĩ Giàu Và Làm Giàu (Think & Grow Rich)",
                            Category = "Kinh tế & Làm giàu",
                            DetailAuthor = "Napoleon Hill - Cố vấn cho hai đời Tổng thống Hoa Kỳ Woodrow Wilson và Franklin D. Roosevelt.",
                            ImageUrl = "/images/nghi-giau-lam-giau.png",
                            InformationAuthor = "Tác giả truyền cảm hứng thành công vĩ đại nhất thế kỷ 20.",
                            Price = 92000m,
                            Subtitle = "Bản đồ tư duy tài chính được đúc kết từ 500 nhân vật giàu có và quyền lực nhất lịch sử.",
                            Title = "13 Nguyên Tắc Nghĩ Giàu Làm Giàu Bất Biến",
                            TitleReview = "Cẩm nang làm giàu kinh điển làm thay đổi tư duy tài chính của hàng triệu triệu phú."
                        },
                        new
                        {
                            BookId = 4,
                            BookName = "Quẳng Gánh Lo Đi & Vui Sống",
                            Category = "Tâm lý & Cuộc sống",
                            DetailAuthor = "Dale Carnegie - Tác giả huyền thoại của phong trào phát triển bản thân.",
                            ImageUrl = "/images/quang-ganh-lo-di.png",
                            InformationAuthor = "Bậc thầy về truyền cảm hứng và tâm lý học ứng dụng.",
                            Price = 84000m,
                            Subtitle = "Sống trọn vẹn trong từng khoảnh khắc hiện tại và đánh thức nguồn năng lượng tích cực.",
                            Title = "Bí Quyết Làm Chủ Tâm Trí & Giải Tỏa Lo Âu",
                            TitleReview = "Liều thuốc an thần tuyệt vời giúp bạn vượt qua áp lực, căng thẳng của cuộc sống hiện đại."
                        },
                        new
                        {
                            BookId = 5,
                            BookName = "Ai Lấy Miếng Pho Mát Của Tôi?",
                            Category = "Kỹ năng sống",
                            DetailAuthor = "Spencer Johnson, M.D. - Tiến sĩ y khoa, diễn giả và tác giả sách bán chạy số 1 New York Times.",
                            ImageUrl = "/images/ai-lay-mieng-pho-mat.png",
                            InformationAuthor = "Chuyên gia hàng đầu về tâm lý học và quản trị hành vi con người.",
                            Price = 65000m,
                            Subtitle = "Câu chuyện ngụ ngôn sâu sắc về sự thay đổi nơi công sở và cuộc sống.",
                            Title = "Nghệ Thuật Thích Nghi Với Mọi Biến Động Cuộc Đời",
                            TitleReview = "Cuốn sách nhỏ làm bừng tỉnh tư duy đổi mới của các tập đoàn hàng đầu thế giới."
                        },
                        new
                        {
                            BookId = 6,
                            BookName = "Ngày Xưa Có Một Con Bò...",
                            Category = "Phát triển bản thân",
                            DetailAuthor = "Camilo Cruz, Ph.D - Tiến sĩ khoa học, tác giả nổi tiếng quốc tế về nghệ thuật tạo động lực.",
                            ImageUrl = "/images/ngay-xua-co-mot-con-bo.png",
                            InformationAuthor = "Diễn giả truyền cảm hứng được săn đón tại hơn 30 quốc gia.",
                            Price = 75000m,
                            Subtitle = "Bài học ngụ ngôn thức tỉnh bạn từ bỏ thói quen đổ lỗi và sự tầm thường.",
                            Title = "Phá Bỏ Mọi Lời Biện Hộ Để Bứt Phá Giới Hạn",
                            TitleReview = "Cuốn sách dí dỏm nhưng sắc bén giúp bạn chặt đứt xiềng xích của sự lười biếng và trì hoãn."
                        },
                        new
                        {
                            BookId = 7,
                            BookName = "Tư Duy Tích Cực Tạo Thành Công",
                            Category = "Phát triển bản thân",
                            DetailAuthor = "Napoleon Hill & W. Clement Stone - Sự kết hợp của hai bậc thầy tư duy xuất sắc nhất thế giới.",
                            ImageUrl = "/images/tu-duy-tich-cuc.png",
                            InformationAuthor = "Những nhà kiến tạo triết lý thành công hiện đại.",
                            Price = 89000m,
                            Subtitle = "Chìa khóa vàng mở cánh cửa thành công và thịnh vượng bền vững.",
                            Title = "Sức Mạnh Của Thái Độ Sống Tích Cực (PMA)",
                            TitleReview = "Khẳng định rằng bạn chính là người nắm quyền làm chủ hoàn toàn số phận của mình."
                        },
                        new
                        {
                            BookId = 8,
                            BookName = "Chiếc Lexus Và Cây Ô Liu",
                            Category = "Kinh tế & Xã hội",
                            DetailAuthor = "Thomas L. Friedman - Nhà báo giành 3 giải thưởng báo chí danh giá Pulitzer.",
                            ImageUrl = "/images/chiec-lexus-va-cay-o-liu.png",
                            InformationAuthor = "Cây bút bình luận đối ngoại hàng đầu của báo The New York Times.",
                            Price = 115000m,
                            Subtitle = "Sự giằng co giữa khát vọng hiện đại hóa công nghệ và gìn giữ bản sắc cội nguồn.",
                            Title = "Bức Tranh Toàn Cảnh Về Kỷ Nguyên Toàn Cầu Hóa",
                            TitleReview = "Tác phẩm kinh điển về kinh tế thế giới được giảng dạy tại các trường đại học hàng đầu."
                        },
                        new
                        {
                            BookId = 9,
                            BookName = "Chiến Thắng Con Quỷ Trong Bạn",
                            Category = "Tâm lý & Cuộc sống",
                            DetailAuthor = "Napoleon Hill - Tác giả của cuốn sách huyền thoại Think and Grow Rich.",
                            ImageUrl = "/images/chien-thang-con-quy.png",
                            InformationAuthor = "Cuốn sách từng bị cấm phát hành suốt hơn 70 năm vì tư tưởng quá đột phá.",
                            Price = 95000m,
                            Subtitle = "Cuộc đối thoại kịch tính giữa tác giả và thực thể ma quỷ giam cầm tiềm năng con người.",
                            Title = "Bí Quyết Vượt Qua Nỗi Sợ Hãi Và Tự Do Đích Thực",
                            TitleReview = "Cuốn sách giúp bạn nhận diện những cạm bẫy tâm lý và thức tỉnh sức mạnh vô biên."
                        },
                        new
                        {
                            BookId = 10,
                            BookName = "Con Đường Phía Trước (The Road Ahead)",
                            Category = "Công nghệ thông tin",
                            DetailAuthor = "Bill Gates - Tỷ phú sáng lập tập đoàn công nghệ Microsoft, nhà từ thiện vĩ đại.",
                            ImageUrl = "/images/con-duong-phia-truoc.png",
                            InformationAuthor = "Một trong những bộ óc công nghệ có tầm ảnh hưởng lớn nhất lịch sử.",
                            Price = 110000m,
                            Subtitle = "Dự báo chuẩn xác về kỷ nguyên số, trí tuệ nhân tạo và internet của nhà sáng lập Microsoft.",
                            Title = "Tầm Nhìn Công Nghệ Làm Thay Đổi Tương Lai Nhân Loại",
                            TitleReview = "Góc nhìn tiên phong về cách mạng số và công nghệ định hình thế kỷ 21."
                        },
                        new
                        {
                            BookId = 11,
                            BookName = "Dám Nghĩ Lớn (The Magic of Thinking Big)",
                            Category = "Phát triển bản thân",
                            DetailAuthor = "David J. Schwartz, Ph.D - Giáo sư tại Đại học Georgia, chuyên gia huấn luyện lãnh đạo.",
                            ImageUrl = "/images/dam-nghi-lon.png",
                            InformationAuthor = "Cố vấn phát triển tư duy cho hàng ngàn tập đoàn quốc tế.",
                            Price = 98000m,
                            Subtitle = "Hãy nâng tầm ước mơ và mở rộng chân trời suy nghĩ để gặt hái thành công vượt trội.",
                            Title = "Phép Màu Của Tư Duy Đột Phá Không Giới Hạn",
                            TitleReview = "Cuốn sách mở khóa năng lực tiềm ẩn, chứng minh tư duy quyết định tầm vóc cuộc đời."
                        },
                        new
                        {
                            BookId = 12,
                            BookName = "Đánh Cắp Ý Tưởng (Steal These Ideas!)",
                            Category = "Kinh tế & Làm giàu",
                            DetailAuthor = "Steve Cone - Chuyên gia marketing hàng đầu của các tập đoàn Citigroup, Fidelity.",
                            ImageUrl = "/images/danh-cap-y-tuong.png",
                            InformationAuthor = "Chiến lược gia truyền thông và xây dựng thương hiệu lừng danh.",
                            Price = 88000m,
                            Subtitle = "Kho tàng các ý tưởng kinh doanh và tiếp thị đắt giá áp dụng ngay trong thực tế.",
                            Title = "Bí Mật Marketing Và Sáng Tạo Làm Nên Thành Công",
                            TitleReview = "Cẩm nang thực chiến dành cho mọi người làm kinh doanh và khởi nghiệp sáng tạo."
                        },
                        new
                        {
                            BookId = 13,
                            BookName = "Dám Chấp Nhận",
                            Category = "Tâm lý & Cuộc sống",
                            DetailAuthor = "Ernie Carwile - Cây bút truyền cảm hứng sâu sắc của tủ sách Hạt Giống Tâm Hồn.",
                            ImageUrl = "/images/dam-chap-nhan.png",
                            InformationAuthor = "Nhà văn chữa lành tâm hồn với hàng triệu độc giả yêu mến.",
                            Price = 72000m,
                            Subtitle = "Những câu chuyện dung dị nhưng thấm đẫm tình yêu thương và sự kiên cường.",
                            Title = "Nghị Lực Vượt Lên Nghịch Cảnh & Trưởng Thành",
                            TitleReview = "Gieo vào lòng người đọc niềm tin son sắt vào cuộc sống và sức mạnh của lòng vị tha."
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Entity.OrderForm", b =>
                {
                    b.Property<int>("OrderFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderFormId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("OrderFormId");

                    b.HasIndex("BookId");

                    b.HasIndex("StatusId");

                    b.ToTable("OrderForms");
                });

            modelBuilder.Entity("WebApplication1.Models.Entity.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Description = "Đơn hàng mới tạo",
                            StatusName = "Chờ xác nhận"
                        },
                        new
                        {
                            StatusId = 2,
                            Description = "Đơn hàng đang trên đường giao",
                            StatusName = "Đang giao"
                        },
                        new
                        {
                            StatusId = 3,
                            Description = "Đã giao thành công",
                            StatusName = "Hoàn thành"
                        },
                        new
                        {
                            StatusId = 4,
                            Description = "Đơn hàng đã bị hủy",
                            StatusName = "Đã hủy"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Entity.AdminNotification", b =>
                {
                    b.HasOne("WebApplication1.Models.Entity.OrderForm", "Order")
                        .WithMany()
                        .HasForeignKey("OrderFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebApplication1.Models.Entity.OrderForm", b =>
                {
                    b.HasOne("WebApplication1.Models.Entity.BookInfomation", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Entity.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
