// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003041507_UpdateBookToNhaGiaKim")]
    partial class UpdateBookToNhaGiaKim
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Entity.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WebApplication1.Models.Entity.BookInfomation", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookId"));

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("DetailAuthor")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("InformationAuthor")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("TitleReview")
                        .HasColumnType("text");

                    b.HasKey("BookId");

                    b.ToTable("BookInfomations");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            BookName = "Nhà Giả Kim (The Alchemist)",
                            Category = "Văn học kinh điển",
                            DetailAuthor = "Paulo Coelho - Nhà văn huyền thoại người Brazil, Sứ giả hòa bình của Liên Hợp Quốc.",
                            ImageUrl = "/images/nha-gia-kim.png",
                            InformationAuthor = "Tác giả có sách được dịch ra nhiều thứ tiếng nhất lịch sử (Kỷ lục Guinness thế giới).",
                            Price = 79000m,
                            Subtitle = "Khi bạn thực sự khao khát một điều gì, toàn thể vũ trụ sẽ hợp lực giúp bạn đạt được điều đó.",
                            Title = "Hành Trình Đi Tìm Vận Mệnh & Giấc Mơ",
                            TitleReview = "Kiệt tác văn học kinh điển toàn cầu đã lay động hơn 150 triệu độc giả trên 170 quốc gia."
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Entity.OrderForm", b =>
                {
                    b.Property<int>("OrderFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderFormId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("OrderFormId");

                    b.HasIndex("BookId");

                    b.HasIndex("StatusId");

                    b.ToTable("OrderForms");
                });

            modelBuilder.Entity("WebApplication1.Models.Entity.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Description = "Đơn hàng mới tạo",
                            StatusName = "Chờ xác nhận"
                        },
                        new
                        {
                            StatusId = 2,
                            Description = "Đơn hàng đang trên đường giao",
                            StatusName = "Đang giao"
                        },
                        new
                        {
                            StatusId = 3,
                            Description = "Đã giao thành công",
                            StatusName = "Hoàn thành"
                        },
                        new
                        {
                            StatusId = 4,
                            Description = "Đơn hàng đã bị hủy",
                            StatusName = "Đã hủy"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Entity.OrderForm", b =>
                {
                    b.HasOne("WebApplication1.Models.Entity.BookInfomation", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Entity.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
